---
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  required:
    ':development':
      - gem: 'beaker'
        version: '~> 4.26'
      - gem: 'beaker-rspec'
        version: '~> 6.3'
      - gem: 'beaker-puppet_install_helper'
        version: '~> 0.9.8'
      - gem: 'beaker-module_install_helper'
        version: '~> 0.1.7'
      - gem: 'beaker-hostgenerator'
        version: '~> 1.3'
      - gem: 'beaker-docker'
        version: '~> 0.8.4'
      - gem: 'beaker-puppet'
        version: '~> 1.21'
      - gem: 'fog-openstack'
        version: '~> 1.0'
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
      - gem: 'public_suffix'
        version: '~> 4.0'
      - gem: 'puppet-lint-absolute_classname-check'
        version: '~> 3.0'
      - gem: 'puppet-lint-absolute_template_path'
        version: '~> 1.0'
      - gem: 'puppet-lint-anchor-check'
        version: '~> 1.0'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
        version: '~> 0.1'
      - gem: 'puppet-lint-empty_string-check'
        version: '~> 0.2'
      - gem: 'puppet-lint-file_ensure-check'
        version: '~> 0.3'
      - gem: 'puppet-lint-leading_zero-check'
        version: '~> 0.1'
      - gem: 'puppet-lint-legacy_facts-check'
        version: '~> 1.0'
      - gem: 'puppet-lint-manifest_whitespace-check'
        version: '~> 0.1'
      - gem: 'puppet-lint-param-docs'
        version: '~> 1.6'
      - gem: 'puppet-lint-resource_reference_syntax'
        version: '~> 1.0'
      - gem: 'puppet-lint-spaceship_operator_without_tag-check'
        version: '~> 0.1'
      - gem: 'puppet-lint-strict_indent-check'
        version: '~> 2.0'
      - gem: 'puppet-lint-top_scope_facts-check'
        version: '~> 1.0'
      - gem: 'puppet-lint-topscope-variable-check'
        version: '~> 1.0'
      - gem: 'puppet-lint-trailing_comma-check'
        version: '~> 0.4'
      - gem: 'puppet-lint-trailing_newline-check'
        version: '~> 1.1'
      - gem: 'puppet-lint-undef_in_function-check'
        version: '~> 0.2'
      - gem: 'puppet-lint-unquoted_string-check'
        version: '~> 2.0'
      - gem: 'puppet-lint-variable_contains_upcase'
        version: '~> 1.2'
      - gem: 'puppet-lint-version_comparison-check'
        version: '~> 0.2'
      - gem: 'puppet_metadata'
        version: '~> 0.3.0'
      - gem: 'serverspec'
        version: '~> 2.41'
      - gem: 'vagrant-wrapper'
        version: '~> 2.0'
      - gem: 'voxpupuli-acceptance'
        version: '~> 0.3.0'
      - gem: 'voxpupuli-release'
        version: '~> 1.0'
      - gem: 'webmock'
        version: '~> 3.12'
Rakefile:
  linter_fail_on_warnings: true
  requires:
    - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
